name: architecture
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  #injection
  get_it: ^7.7.0
  #state management
  flutter_bloc: ^8.1.5
  #equatable
  equatable: ^2.0.5
  #localization
  easy_localization: ^3.0.5
  #local db
  hive: ^2.2.3
  #path provider
  path_provider: ^2.1.3
  #networking
  dio: ^5.4.3+1
  dio_retry_plus: ^2.0.6
  #retrofit
  retrofit: ^4.1.0
  json_annotation: ^4.8.1
  #gap
  gap: ^3.0.1
  #svg
  flutter_svg: ^2.0.10+1
  #custom toast
  toastification: ^1.2.1
  #native splash
  flutter_native_splash: ^2.4.0
  #for log
  logger: ^2.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  retrofit_generator: ^8.1.0
  json_serializable: ^6.6.2

flutter:


  uses-material-design: true

  assets:
    - assets/locale/
    - assets/png/
    - assets/svg/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
